INSERT INTO CAFE_INFO (EMAIL, CAFE_NAME, BUSINESS_LICENSE, ZIPCODE, CAFE_ADDRESS, CAFE_DETAIL_ADDRESS, PHONE_NUMBER, CAFE_INTRODUCTION, IMAGE, IS_BUSINESS_DAY, OPERATION_TIME_TEXT, CREATED_AT, UPDATED_AT)
VALUES ('taylor1213@gmail.com', '대림창고', '111-22-33333', '04782', '서울특별시 성동구 성수이로 78', '1층', '02-1234-5678', '과거 공장을 개조한 대형 갤러리 카페', '/images/cafe/Cafe1.png', true, '월-금 09:00~18:00', NOW(), NOW());

INSERT INTO CAFE_INFO (EMAIL, CAFE_NAME, BUSINESS_LICENSE, ZIPCODE, CAFE_ADDRESS, CAFE_DETAIL_ADDRESS, PHONE_NUMBER, CAFE_INTRODUCTION, IMAGE, IS_BUSINESS_DAY, OPERATION_TIME_TEXT, CREATED_AT, UPDATED_AT)
VALUES ('miyeon0131@gmail.com', '텅 성수 스페이스', '222-33-44444', '04783', '서울특별시 성동구 연무장길 8-1', '2층', '02-2345-6789', '미니멀한 인테리어와 감각적인 공간 구성의 카페', '/images/cafe/Cafe2.png', true, '월-토 10:00~19:00', NOW(), NOW());

INSERT INTO CAFE_INFO (EMAIL, CAFE_NAME, BUSINESS_LICENSE, ZIPCODE, CAFE_ADDRESS, CAFE_DETAIL_ADDRESS, PHONE_NUMBER, CAFE_INTRODUCTION, IMAGE, IS_BUSINESS_DAY, OPERATION_TIME_TEXT, CREATED_AT, UPDATED_AT)
VALUES ('yuqi0923@gmail.com', '오우드', '333-44-55555', '04784', '서울특별시 성동구 연무장길 101-1', '2층', '02-3456-7890', '자연광이 가득한 통유리창과 브런치를 즐길 수 있는 감성 카페', '/images/cafe/Cafe3.png', true, '매일 09:30~20:00', NOW(), NOW());

INSERT INTO CAFE_INFO (EMAIL, CAFE_NAME, BUSINESS_LICENSE, ZIPCODE, CAFE_ADDRESS, CAFE_DETAIL_ADDRESS, PHONE_NUMBER, CAFE_INTRODUCTION, IMAGE, IS_BUSINESS_DAY, OPERATION_TIME_TEXT, CREATED_AT, UPDATED_AT)
VALUES ('minmin@gmail.com', '기미사 성수', '444-55-66666', '04785', '서울특별시 성동구 성수이로26길 47', '1층', '02-4567-8901', '스페셜티 커피와 오마카세 스타일의 음료 코스를 제공하는 카페', '/images/cafe/Cafe4.png', true, '화-일 11:00~22:00', NOW(), NOW());

INSERT INTO CAFE_INFO (EMAIL, CAFE_NAME, BUSINESS_LICENSE, ZIPCODE, CAFE_ADDRESS, CAFE_DETAIL_ADDRESS, PHONE_NUMBER, CAFE_INTRODUCTION, IMAGE, IS_BUSINESS_DAY, OPERATION_TIME_TEXT, CREATED_AT, UPDATED_AT)
VALUES ('shushu@gmail.com', '할아버지 공장', '555-66-77777', '04786', '서울특별시 성동구 성수이로7가길 9', '1층', '02-5678-9012', '공장을 개조한 창고형 카페로, 넓은 야외 공간과 애견 동반이 가능', '/images/cafe/Cafe5.png', true, '매일 10:00~21:00', NOW(), NOW());

INSERT INTO CAFE_INFO (EMAIL, CAFE_NAME, BUSINESS_LICENSE, ZIPCODE, CAFE_ADDRESS, CAFE_DETAIL_ADDRESS, PHONE_NUMBER, CAFE_INTRODUCTION, IMAGE, IS_BUSINESS_DAY, OPERATION_TIME_TEXT, CREATED_AT, UPDATED_AT)
VALUES ('soyoen0502@gmail.com', '따우전드 성수', '666-77-88888', '04782', '서울특별시 성동구 연무장1길 7', '1층', '02-1000-0001', '빈티지한 감성의 브런치 카페', '/images/cafe/Cafe6.png', true, '월-금 08:00~18:00', NOW(), NOW());

INSERT INTO CAFE_INFO (EMAIL, CAFE_NAME, BUSINESS_LICENSE, ZIPCODE, CAFE_ADDRESS, CAFE_DETAIL_ADDRESS, PHONE_NUMBER, CAFE_INTRODUCTION, IMAGE, IS_BUSINESS_DAY, OPERATION_TIME_TEXT, CREATED_AT, UPDATED_AT)
VALUES ('anyujin0901@gmail.com', '헨리스플랏', '777-88-99999', '04783', '서울특별시 성동구 뚝섬로 427-8', '2층', '02-1000-0002', '모던한 인테리어의 커피 전문점', '/images/cafe/Cafe7.png', true, '월-토 10:00~22:00', NOW(), NOW());

INSERT INTO CAFE_INFO (EMAIL, CAFE_NAME, BUSINESS_LICENSE, ZIPCODE, CAFE_ADDRESS, CAFE_DETAIL_ADDRESS, PHONE_NUMBER, CAFE_INTRODUCTION, IMAGE, IS_BUSINESS_DAY, OPERATION_TIME_TEXT, CREATED_AT, UPDATED_AT)
VALUES ('jangwonyoung0831@gmail.com', '에이치커피로스터스', '888-99-00000', '04784', '서울특별시 성동구 연무장길 8-1', '1층', '02-1000-0003', '스페셜티 커피를 제공하는 로스터리 카페', '/images/cafe/Cafe8.png', true, '수-일 12:00~20:00', NOW(), NOW());

INSERT INTO CAFE_INFO (EMAIL, CAFE_NAME, BUSINESS_LICENSE, ZIPCODE, CAFE_ADDRESS, CAFE_DETAIL_ADDRESS, PHONE_NUMBER, CAFE_INTRODUCTION, IMAGE, IS_BUSINESS_DAY, OPERATION_TIME_TEXT, CREATED_AT, UPDATED_AT)
VALUES ('liz1121@gmail.com', '테디스오븐', '999-00-11111', '04785', '서울특별시 성동구 서울숲2길 19-18', '1층', '02-1000-0004', '프랑스식 베이커리와 디저트를 즐길 수 있는 카페', '/images/cafe/Cafe9.png', true, '매일 10:00~19:00', NOW(), NOW());
